//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderingConfigurations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderingConfigurations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assessment.Resources.OrderingConfigurations", typeof(OrderingConfigurations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Property&quot;:&quot;Author&quot;,&quot;Direction&quot;:&quot;Ascending&quot;}.
        /// </summary>
        public static string AuthorAscending {
            get {
                return ResourceManager.GetString("AuthorAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Property&quot;:&quot;Author&quot;,&quot;Direction&quot;:&quot;Descending&quot;}.
        /// </summary>
        public static string AuthorDescending {
            get {
                return ResourceManager.GetString("AuthorDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Property&quot;:&quot;Edition&quot;,&quot;Direction&quot;:&quot;Ascending&quot;}.
        /// </summary>
        public static string EditionAscending {
            get {
                return ResourceManager.GetString("EditionAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Property&quot;:&quot;Edition&quot;,&quot;Direction&quot;:&quot;Descending&quot;}.
        /// </summary>
        public static string EditionDescending {
            get {
                return ResourceManager.GetString("EditionDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Property&quot;:&quot;Title&quot;,&quot;Direction&quot;:&quot;Ascending&quot;}.
        /// </summary>
        public static string TitleAscending {
            get {
                return ResourceManager.GetString("TitleAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Property&quot;:&quot;Title&quot;,&quot;Direction&quot;:&quot;Descending&quot;}.
        /// </summary>
        public static string TitleDescending {
            get {
                return ResourceManager.GetString("TitleDescending", resourceCulture);
            }
        }
    }
}
